### PR TITLE
util: add average jitter to `rttEstimator` & expose stats of pipelines to caller

### PR DESCRIPTION
**Pull request by chavoosh**

### CODE REVIEW

**Comment by chavoosh** [comment]
Jeff, as you properly pointed it out last time about breaking the changes to smaller commits, I broke down this change to 7 commits.
Previously, pipelines were not able to expose the content retrieval statistics (e.g., average delay, average jitter, number of timeouts, nacks, etc.) to the caller application. This change implements a stats collecting API to let any application see the performance of the content retrieval process, using either `Fixed` or `Cubic` pipeline.

**Comment by jefft0** [comment]
Thanks for using smaller commits. It helps a lot. One request: Can you document the stats param in the doc comment for SegmentFetcher.fetch?

**Comment by jefft0** [comment]
... While you're at it can you also document the opts param of SegmentFetcher.fetch? Make sure it says that it is (optional) and what is the behavior if the param is omitted, like this:

https://github.com/named-data/ndn-js/blob/master/js/security/key-chain.js#L485

The final parameters of SegmentFetcher.fetch are optional. What happens if the caller includes stats but omits opts? Will the code try to use the stats as the opts param?

**Comment by chavoosh** [comment]
I have pushed 2 more commits, the first one applies your comments (i.e., updating `SegmentFetcher`'s documentation) and the second one replaces an error message in `fixed` and `cubic` pipelines with a handle failure call.

**Pull request merged**
