### PR TITLE
util: update pipelines printSummary message (now includes completion time)

### PR DESCRIPTION
**Pull request by chavoosh**

### CODE REVIEW

**Comment by jefft0** [comment]
I notice `Log.LOG = 5;` in ndn.js, but not in the main source code files. Do you need to rebuild ndn.js? (The library code should not change the LOG level.)

**Comment by chavoosh** [comment]
Yes, I just rebuild `ndn.js` and `ndn.min.js` and pushed the code.

**Comment by jefft0** [comment]
Are you sure you pushed? I don't see it.

**Comment by chavoosh** [comment]
I `force-pushed` it.

**Comment by chavoosh** [comment]
You should be able to see that the `LOG` is no longer in build files, now...

**Pull request merged**
