### PR TITLE
util: assign the values to `stats` object in pipeline, instead of overriding them

### PR DESCRIPTION
**Pull request by chavoosh**
Instead of populating the `stats` object passed by segment fetcher, pipelines were overriding the object (which does not change the original object). The bug is resolved.

### CODE REVIEW

**Comment by jefft0** [comment]
Hi Chavoosh.  I merged the pull request too early. When I run [test-list-faces](https://github.com/named-data/ndn-js/blob/master/examples/browser/test-list-faces.html), I get the following error:

    Error in onData: TypeError: this.stats is undefined

In the constructor, if stats is null, you need to assign it to an empty object.
https://github.com/named-data/ndn-js/blob/65d1b740b5d5ac16460e5150f5c5a9bf4d7717a5/js/util/pipeline-cubic.js#L102
https://github.com/named-data/ndn-js/blob/65d1b740b5d5ac16460e5150f5c5a9bf4d7717a5/js/util/pipeline-fixed.js#L107

**Comment by jefft0** [comment]
Can you do another quick pull request to fix this?

**Comment by jefft0** [comment]
Something like:

    this.stats = stats != null ? stats : {};

**Comment by chavoosh** [comment]
Absolutely, thanks for reporting the bug. I'll push the commit in a few minutes.

**Pull request merged**
