### PR TITLE
Add control parameters fields

### PR DESCRIPTION
**Pull request by andrewsbrown**
Note that the fix for DecodingException may (or may not) need to be applied to all exceptions; maybe we should change the default Exception constructor to something more like Exception(message, [optional] error).

### CODE REVIEW

**Comment by jefft0** [comment]
I don't think we need to change DecodingException. Some code in 2 files was creating it incorrectly. I created a bug report and fixed it. http://redmine.named-data.net/issues/2439

**Comment by jefft0** [comment]
It looks like you changed how the ControlParameters URI is handled from the jNDN code. I would prefer to keep it the same. In jNDN if the URI is omitted then it is an empty string but in NDN-JS you changed it to null. Also, then encoding of the URI is different.  Here is the jNDN code it uses Blob to UTF8-encode the string:

https://github.com/named-data/jndn/blob/ba562515ffe47601e704d32d6f27282623274d01/src/net/named_data/jndn/encoding/Tlv0_1_1WireFormat.java#L312

But here is the NDN-JS code:

https://github.com/andrewsbrown/ndn-js/blob/add-control-parameters-fields/js/encoding/tlv-0_1_1-wire-format.js#L291

Why not make it the same?

**Comment by andrewsbrown** [comment]
Good point; for some reason I though the encoder needed a null in `writeOptionalBlobTlv()` (https://github.com/andrewsbrown/ndn-js/blob/add-control-parameters-fields/js/encoding/tlv/tlv-encoder.js#L219) but it doesn't. I'll modify tomorrow.

**Comment by andrewsbrown** [comment]
@jefft0, I changed the default URI value to an empty string and everything works great; apparently `writeOptionalBlobTlv()` checks if the given value is null or an empty string before writing it. 

As for matching jndn exactly, the line you quote above only wraps URI in a Blob in order to get a Buffer; in ndn-js, the DynamicBuffer that does `copyFromBack()` does this for us--in other words, doing a wrap like `new Blob(controlParameters.getUri()).buf()` is unnecessary since `controlParameters.getUri()` is wrapped in a `new Buffer()` later. Do you still want to wrap it?

**Comment by jefft0** [comment]
It is not merely wrapping the string. Remember that Java and JavaScript strings are Unicode. To convert from a string to a byte array requires encoding a (possibly Chinese) string in UTF8. This is what the Blob constructor does when handed a string. And this is why you can't directly call  writeOptionalBlobTlv with a string. I know "URI" is supposed to be restricted to ASCII values, but let's do the (Unicode) string handling properly.

https://github.com/named-data/jndn/blob/ec0728be484f1f38a5a8dd64e992abd73dcbaac2/src/net/named_data/jndn/util/Blob.java#L119

https://github.com/named-data/ndn-js/blob/32cbb5dbb7011f8df6d15b6fe9b2c955ba278d8a/js/util/blob.js#L49

**Comment by andrewsbrown** [comment]
@jefft0, good call, makes sense

**Comment by andrewsbrown** [comment]
@jefft0, this should be good to go but we may want to squash the commits into one big one.

**Comment by jefft0** [comment]
Hi Andrew. I merged your pull request. You asked about squashing into one commit, but I prefer separate commits. This way you get a better history when you view the commit messages for a single file.

I changed the test script in package.json, some of the unit tests that load test files expect to be run from the unit-tests folder. So I change it from "mocha tests/node/unit-tests --timeout 10000" to "cd tests/node/unit-tests ; mocha . --timeout 10000 ; cd ../../..".  Does that sound right?

**Pull request merged**
